name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@main
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          check-latest: true
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.0.x'
    

      - name: Install dependencies
        run: flutter pub get

      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze .
        
      - name: Run tests
        run: flutter test
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
